### ISSUE TITLE
Doesn't work with a symlink dir

### ISSUE THREAD

**Issue by ddollar** [bmizerany/vendor#1]
I have a symlink like this: `ln -s $GOPATH/src/github.com/ddollar/foo ~/src/foo` and I work out of the `~/src/foo` directory.

When I work out of this directory `vendor ./...` does not work as expected and vendors many of the subpackages of foo.

If I go straight to the GOPATH directory it works as expected.

**Comment by bmizerany** [comment]
May I ask why you're working out of a symlink dir?

**Comment by bmizerany** [comment]
@ddollar Does `go list ./...` work in the symlink?
