### ISSUE TITLE
Vendoring issues

### ISSUE THREAD

**Issue by ddollar** [bmizerany/vendor#2]
```
# github.com/convox/rack/vendor/golang.org/x/crypto/poly1305
../../../Go/src/github.com/convox/rack/vendor/golang.org/x/crypto/poly1305/sum_amd64.go:13: missing function body for "poly1305"
# github.com/convox/rack/vendor/golang.org/x/crypto/salsa20/salsa
../../../Go/src/github.com/convox/rack/vendor/golang.org/x/crypto/salsa20/salsa/salsa20_amd64.go:13: missing function body for "salsa2020XORKeyStream"
```

Not sure what's going on here but these function bodies are implemented in .s files.

**Comment by bmizerany** [comment]
Do you have these files somewhere public and instructions on how to reproduce?

**Comment by ddollar** [comment]
https://github.com/convox/rack/tree/vendor

**Comment by ddollar** [comment]
FWIW here's the diff when I vendor with the latest godep:

https://github.com/convox/rack/commit/74c276450b5504bed0cb6125b3128db1737ca123

**Comment by bmizerany** [comment]
@ddollar What command are you running and from what directory? What does your GOPATH look like?

**Comment by ddollar** [comment]
GOPATH is `~/Go` and the command I'm running is `vendor ./...`

**Comment by bmizerany** [comment]
please `go get` the latest and try again. (force pushed)

**Comment by bmizerany** [comment]
I was able to get convox building with vendor. I had to remove all Godeps dirs and strip all of `github.com/convox/{rack,release}/Godeps/_workspace/src/` from rack and release. Vendor will also refuse to try to figure out what to do when it finds a vendor in a vendor. There are many good reasons for this. Convox has a few deps with vendors in them, so I just manually ran vendor for the three and then it all worked.

**Comment by bmizerany** [comment]
Please close if you get it working.

**Comment by ddollar** [comment]
How do I know what extra things I need to run for vendors-in-vendors?

**Comment by bmizerany** [comment]
It outputs to stderr the import paths in a warning. I have an idea to make it more clear and collapse them into a nice list. For now I just copy the path and rerun vendor with them.
